// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CardValidation.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CardOwnerValidationFeature : object, Xunit.IClassFixture<CardOwnerValidationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public CardOwnerValidationFeature(CardOwnerValidationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Card Owner Validation", "  As a payment processing system\r\n  I want to validate credit card owner names\r\n " +
                    " So that only valid owner names are accepted", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the card validation service is available at \"https://cardvalidation.api:7135/Card" +
                    "Validation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Valid owner names should be accepted")]
        [Xunit.TraitAttribute("FeatureTitle", "Card Owner Validation")]
        [Xunit.TraitAttribute("Description", "Valid owner names should be accepted")]
        [Xunit.InlineDataAttribute("John", new string[0])]
        [Xunit.InlineDataAttribute("John Doe", new string[0])]
        [Xunit.InlineDataAttribute("John Doe Smith", new string[0])]
        [Xunit.InlineDataAttribute("Mary Jane Watson", new string[0])]
        [Xunit.InlineDataAttribute("A B C", new string[0])]
        public async System.Threading.Tasks.Task ValidOwnerNamesShouldBeAccepted(string ownerName, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ownerName", ownerName);
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Valid owner names should be accepted", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table14 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "owner",
                            string.Format("{0}", ownerName)});
                table14.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table14.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table14.AddRow(new string[] {
                            "cvv",
                            "123"});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table14, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should indicate payment system type \"Visa\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Invalid owner names should return validation error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card Owner Validation")]
        [Xunit.TraitAttribute("Description", "Invalid owner names should return validation error")]
        [Xunit.InlineDataAttribute("John123", new string[0])]
        [Xunit.InlineDataAttribute("John-Doe", new string[0])]
        [Xunit.InlineDataAttribute("John_Doe", new string[0])]
        [Xunit.InlineDataAttribute("John@Doe", new string[0])]
        [Xunit.InlineDataAttribute("John.Doe", new string[0])]
        [Xunit.InlineDataAttribute("John  Doe", new string[0])]
        [Xunit.InlineDataAttribute("John Doe Smith Jr", new string[0])]
        [Xunit.InlineDataAttribute("John Doe Smith Jr Brown", new string[0])]
        [Xunit.InlineDataAttribute("123", new string[0])]
        [Xunit.InlineDataAttribute("@#$%", new string[0])]
        public async System.Threading.Tasks.Task InvalidOwnerNamesShouldReturnValidationError(string ownerName, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ownerName", ownerName);
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Invalid owner names should return validation error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table15 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table15.AddRow(new string[] {
                            "owner",
                            string.Format("{0}", ownerName)});
                table15.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table15.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table15.AddRow(new string[] {
                            "cvv",
                            "123"});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table15, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Wrong owner\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty owner name should return required field error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card Owner Validation")]
        [Xunit.TraitAttribute("Description", "Empty owner name should return required field error")]
        public async System.Threading.Tasks.Task EmptyOwnerNameShouldReturnRequiredFieldError()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Empty owner name should return required field error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table16 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "owner",
                            ""});
                table16.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table16.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table16.AddRow(new string[] {
                            "cvv",
                            "123"});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table16, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Owner is required\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Missing owner field should return required field error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card Owner Validation")]
        [Xunit.TraitAttribute("Description", "Missing owner field should return required field error")]
        public async System.Threading.Tasks.Task MissingOwnerFieldShouldReturnRequiredFieldError()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Missing owner field should return required field error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table17 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table17.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table17.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table17.AddRow(new string[] {
                            "cvv",
                            "123"});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table17, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Owner is required\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CardOwnerValidationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CardOwnerValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
