// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CardValidation.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CardCVVValidationFeature : object, Xunit.IClassFixture<CardCVVValidationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public CardCVVValidationFeature(CardCVVValidationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Card CVV Validation", "  As a payment processing system\r\n  I want to validate credit card CVV codes\r\n  S" +
                    "o that only valid CVV codes are accepted", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("the card validation service is available at \"https://cardvalidation.api:7135/Card" +
                    "Validation/card/credit/validate\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Valid CVV codes should be accepted")]
        [Xunit.TraitAttribute("FeatureTitle", "Card CVV Validation")]
        [Xunit.TraitAttribute("Description", "Valid CVV codes should be accepted")]
        [Xunit.InlineDataAttribute("4111111111111111", "123", "Visa", new string[0])]
        [Xunit.InlineDataAttribute("4111111111111111", "999", "Visa", new string[0])]
        [Xunit.InlineDataAttribute("4111111111111111", "000", "Visa", new string[0])]
        [Xunit.InlineDataAttribute("5555555555554444", "456", "MasterCard", new string[0])]
        [Xunit.InlineDataAttribute("5555555555554444", "789", "MasterCard", new string[0])]
        [Xunit.InlineDataAttribute("371449635398431", "1234", "AmericanExpress", new string[0])]
        [Xunit.InlineDataAttribute("371449635398431", "9999", "AmericanExpress", new string[0])]
        [Xunit.InlineDataAttribute("371449635398431", "0000", "AmericanExpress", new string[0])]
        public async System.Threading.Tasks.Task ValidCVVCodesShouldBeAccepted(string cardNumber, string cvv, string paymentSystem, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("cardNumber", cardNumber);
            argumentsOfScenario.Add("cvv", cvv);
            argumentsOfScenario.Add("paymentSystem", paymentSystem);
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Valid CVV codes should be accepted", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table1 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "owner",
                            "John Doe"});
                table1.AddRow(new string[] {
                            "number",
                            string.Format("{0}", cardNumber)});
                table1.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table1.AddRow(new string[] {
                            "cvv",
                            string.Format("{0}", cvv)});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table1, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync(string.Format("the response should indicate payment system type \"{0}\"", paymentSystem), ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Invalid CVV codes should return validation error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card CVV Validation")]
        [Xunit.TraitAttribute("Description", "Invalid CVV codes should return validation error")]
        [Xunit.InlineDataAttribute("12", new string[0])]
        [Xunit.InlineDataAttribute("1", new string[0])]
        [Xunit.InlineDataAttribute("12345", new string[0])]
        [Xunit.InlineDataAttribute("abc", new string[0])]
        [Xunit.InlineDataAttribute("12a", new string[0])]
        [Xunit.InlineDataAttribute("1a3", new string[0])]
        [Xunit.InlineDataAttribute("a23", new string[0])]
        [Xunit.InlineDataAttribute("12-3", new string[0])]
        [Xunit.InlineDataAttribute("12.3", new string[0])]
        [Xunit.InlineDataAttribute("12 3", new string[0])]
        public async System.Threading.Tasks.Task InvalidCVVCodesShouldReturnValidationError(string cvv, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("cvv", cvv);
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Invalid CVV codes should return validation error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table2 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "owner",
                            "John Doe"});
                table2.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table2.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table2.AddRow(new string[] {
                            "cvv",
                            string.Format("{0}", cvv)});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table2, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Wrong cvv\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty CVV should return required field error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card CVV Validation")]
        [Xunit.TraitAttribute("Description", "Empty CVV should return required field error")]
        public async System.Threading.Tasks.Task EmptyCVVShouldReturnRequiredFieldError()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Empty CVV should return required field error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table3 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "owner",
                            "John Doe"});
                table3.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table3.AddRow(new string[] {
                            "date",
                            "12/2025"});
                table3.AddRow(new string[] {
                            "cvv",
                            ""});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table3, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Cvv is required\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Missing CVV field should return required field error")]
        [Xunit.TraitAttribute("FeatureTitle", "Card CVV Validation")]
        [Xunit.TraitAttribute("Description", "Missing CVV field should return required field error")]
        public async System.Threading.Tasks.Task MissingCVVFieldShouldReturnRequiredFieldError()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Missing CVV field should return required field error", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                Reqnroll.Table table4 = new Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "owner",
                            "John Doe"});
                table4.AddRow(new string[] {
                            "number",
                            "4111111111111111"});
                table4.AddRow(new string[] {
                            "date",
                            "12/2025"});
                await testRunner.GivenAsync("I have a credit card with the following details:", ((string)(null)), table4, "Given ");
                await testRunner.WhenAsync("I send the validation request", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("the response status code should be 400", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
                await testRunner.AndAsync("the response should contain error message \"Cvv is required\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CardCVVValidationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CardCVVValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
